import hashlib
import py_compile
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

PYTHON_ARTIFACTS = (
    "tools/data-preparation/convert_heic.py",
    "tools/data-preparation/capture_frames.py",
    "tools/data-preparation/label_four_points.py",
    "tools/data-preparation/auto_label.py",
    "tools/data-preparation/review_labels.py",
    "tools/data-preparation/split_dataset.py",
    "training/train.py",
    "evaluation/evaluate_detector.py",
    "demo/desktop_demo.py",
    "deployment/bench_camera.py",
)

IMAGE_ARTIFACTS = (
    "docs/images/detector-metric-summary.png",
    "docs/images/training-validation-loss.png",
    "docs/images/helipad-label-example.png",
    "docs/images/realsense-system-overview.svg",
)
BANNED_TEAM_REALSENSE_IMAGE_SHA256 = "28d8419ca8278d520906dce273e04baa148f4f4a520383d112f15c4b0731c40f"

WINDOWS_ABSOLUTE_PATH = re.compile(r"(?i)(?<![A-Z0-9_])[A-Z]:[\\\\/]")
FORBIDDEN_SECRET_OUTPUT = (
    re.compile(r"(?i)docker\s+inspect[^\n]*\.Config\.Env"),
    re.compile(r"(?i)print\s*\(\s*(?:os\.)?environ"),
    re.compile(r"(?i)print\s*\([^\n]*(?:api[_-]?key|token|password|secret)"),
)
INTERNAL_ASSISTANT_MARKER = re.compile(r"(?i)\b(?:chatgpt|codex|generated by ai)\b")


def test_expected_portfolio_sources_and_images_exist():
    missing = [path for path in (*PYTHON_ARTIFACTS, *IMAGE_ARTIFACTS) if not (ROOT / path).is_file()]
    assert not missing, f"missing portfolio artifacts: {missing}"


def test_portfolio_python_sources_are_portable_and_secret_safe():
    production_sources = sorted(
        path for path in ROOT.rglob("*.py")
        if ".git" not in path.parts and "tests" not in path.parts
    )
    for path in production_sources:
        relative = path.relative_to(ROOT).as_posix()
        text = path.read_text(encoding="utf-8")
        assert not WINDOWS_ABSOLUTE_PATH.search(text), f"Windows absolute path in {relative}"
        assert not INTERNAL_ASSISTANT_MARKER.search(text), f"internal assistant marker in {relative}"
        for pattern in FORBIDDEN_SECRET_OUTPUT:
            assert not pattern.search(text), f"secret-output pattern in {relative}: {pattern.pattern}"


def test_portfolio_python_sources_compile(tmp_path):
    production_sources = sorted(
        path for path in ROOT.rglob("*.py")
        if ".git" not in path.parts and "tests" not in path.parts
    )
    for index, path in enumerate(production_sources):
        py_compile.compile(
            str(path),
            cfile=str(tmp_path / f"artifact-{index}.pyc"),
            doraise=True,
        )


def test_only_approved_portfolio_media_and_no_raw_reports():
    image_dir = ROOT / "docs" / "images"
    actual_images = {path.relative_to(ROOT).as_posix() for path in image_dir.iterdir() if path.is_file()}
    assert actual_images == set(IMAGE_ARTIFACTS)

    forbidden_suffixes = {".avi", ".docx", ".mov", ".mp4", ".pdf", ".pptx"}
    forbidden = [
        path.relative_to(ROOT).as_posix()
        for path in ROOT.rglob("*")
        if path.is_file() and ".git" not in path.parts and path.suffix.lower() in forbidden_suffixes
    ]
    assert not forbidden, f"raw report/video artifacts are not allowed: {forbidden}"


def test_realsense_overview_is_original_and_self_contained():
    visual = ROOT / "docs" / "images" / "realsense-system-overview.svg"
    assert visual.is_file()
    svg = visual.read_text(encoding="utf-8")
    assert not re.search(r"(?i)<image\b|href\s*=\s*[\"']https?://", svg)
    assert hashlib.sha256(visual.read_bytes()).hexdigest() != BANNED_TEAM_REALSENSE_IMAGE_SHA256
